#!/bin/bash

_prefix=$HOME/.local/bin
[ ${1:-x} = x ] || _prefix=$1

echo -n ln -s $PWD/dim.sh $_prefix/dim
        ln -s $PWD/dim.sh $_prefix/dim &>/dev/null && \
echo -e ' [ \e[01;32mOK\e[0m ]' || \
echo -e ' [ \e[01;31mFAIL\e[0m ]'
