#!/bin/bash

command -v dim &>/dev/null && {
	echo -n '  dim found at: '
	command -v dim
	exit 0
}

dimdir=$(dirname $(readlink -f $0))

[[ ${1:-x} == /* ]] && {
	prefix=$1/bin
	shift
}
[[ ${1:-x} == -* ]] || {
	prefix=$PWD/$1/bin
	shift
}
[ ${prefix:-x} = x ] && {
	[ $EUID -eq 0 ] && \
		prefix=/bin || \
		prefix=~/.local/bin
}
[ ${1:-x} = -q ] && {
	prefix=$(echo $prefix | sed s:/bin::)
}

[ -e $prefix ] || {
	echo warn: md prefix $prefix
	mkdir -p $prefix
}

echo -n "  symlink $dimdir/dim.sh ->> $prefix/dim"

echo
exit

ln -fs $dimdir/dim.sh $prefix/dim &>/dev/null && \
echo -e ' [ \e[01;32mOK\e[0m ]' || \
echo -e ' [ \e[01;31mFAIL\e[0m ]'

unset dimdir prefix
