#!/bin/bash

# Usage: symlink [PREFIX]

prefix=${1:-~/.local/bin}
echo -n ln -s $PWD/dim.sh $prefix/dim
        ln -s $PWD/dim.sh $prefix/dim &>/dev/null && \
echo -e ' [ \e[1;32mDONE\e[m ]' || \
echo -e ' [ \e[1;31mFAIL\e[m ]'
